### ISSUE TITLE
[AVM Module Issue]: Export Sub Resources so that their ID's can be referenced without an extra data resource

### ISSUE THREAD

**Issue by jchancellor-ms** [Azure/terraform-azurerm-avm-res-network-loadbalancer#22]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Module specific issue

- [X] I confirm that this issue is about this AVM module and not about the resource itself, or how to use Terraform.

### Issue Type?

Feature Request

### Description

Sub-resource details for resources like NAT rules and Backend Pools aren't contained in the load-balancer resource output.  Please include sub resource details as an output.  This will allow for referencing things like backend pool and NAT rule ID's.

**Comment by donovm4** [comment]
outputs for bepool and nat rule now available in `v0.1.7`
