### ISSUE TITLE
[AVM Module Issue]: New modtm provider added is causing issues in init

### ISSUE THREAD

**Issue by Anutolearn** [Azure/terraform-azurerm-avm-res-network-loadbalancer#59]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

v0.2.1

### Description

Terraform init is failing looking for modtm provider. Path given in telemetry is "https://registry.terraform.io/providers/hashicorp/modtm/latest/docs/data-sources/module_source" instead of "https://registry.terraform.io/providers/Azure/modtm/latest/docs/data-sources/module_source". 

This issue is fixed in [terraform-azurerm-avm-res-compute-virtualmachine] pull request # 98
Please help to resolve in this module. Thank you!

│ Error: Failed to query available provider packages
│
│ Could not retrieve the list of available versions for provider hashicorp/modtm: provider registry registry.terraform.io does not h not have a provider named registry.terraform.io/hashicorp/modtm

**Comment by donovm4** [comment]
Hi @Anutolearn - will look into this fix soon.

**Comment by donovm4** [comment]
@Anutolearn - please review the latest release (v0.2.2)

**Comment by Anutolearn** [comment]
Thank you @donovm4 Issue is now fixed.
